### ISSUE TITLE
 Unknown jdwp-command: 1/12

### ISSUE THREAD

**Issue by MikeGrateful** [srogmann/jsmud-analysis#1]
hi ,    be in trouble in org/rogmann/jsmud/dumps/JdwpProxy.java

Exception in thread "pool-1-thread-1" java.lang.RuntimeException: Unknown jdwp-command: 1/12
	at org.rogmann.jsmud.dumps.JdwpParser.addPart(JdwpParser.java:105)
	at org.rogmann.jsmud.dumps.JdwpProxy.lambda$processRelaying$0(JdwpProxy.java:94)

![image](https://user-images.githubusercontent.com/15280143/186979853-1ad0931d-c40b-4507-98cc-c53b0093c41e.png)

env jdk 1.8.0_161

java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5050 -Xms512m -Xmx1024m -XX:PermSize=64m -XX:MaxPermSize=512m -jar  compiler-0.0.1-SNAPSHOT.jar

**Comment by srogmann** [comment]
Hi, I didn't know that there are debuggers which use Capabilities (cmd 1/12) instead of CapabilitiesNew (cmd 1/17).

I added the Capabilities command (cmd 1/12) in class JdwpParser.

**Comment by srogmann** [comment]
JdwpCommandProcessor had been extended, too.
